version: '2'
services:
  mysql:
    image: openzipkin/zipkin-mysql
    ports:
      - "3306:3306"
    networks:
      - opentracing
  zipkin:
    image: openzipkin/zipkin
    environment:
      - STORAGE_TYPE=mysql
      - MYSQL_HOST=mysql
    ports:
      - "9411:9411"
    networks:
      - opentracing
    depends_on:
      - mysql
  publisher:
    image: serrodcal/opentracing-publisher
    build: ./publisher
    volumes:
      - ./publisher/server.yml:/server.yml
      - ./publisher/target/java-docker-opentracing-poc-publisher-1.0-SNAPSHOT.jar:/java-docker-opentracing-poc-publisher-1.0-SNAPSHOT.jar
    ports:
      - "8082:8082"
      - "9082:9082"
    networks:
      - opentracing
    depends_on:
      - mysql
      - zipkin
    command: java -jar java-docker-opentracing-poc-publisher-1.0-SNAPSHOT.jar server server.yml
  formatter:
    image: serrodcal/opentracing-formatter
    build: ./formatter
    volumes:
      - ./formatter/server.yml:/server.yml
      - ./formatter/target/java-docker-opentracing-poc-formatter-1.0-SNAPSHOT.jar:/java-docker-opentracing-poc-formatter-1.0-SNAPSHOT.jar
    ports:
      - "8082:8082"
      - "9082:9082"
    networks:
      - opentracing
    depends_on:
      - mysql
      - zipkin
    command: java -jar java-docker-opentracing-poc-formatter-1.0-SNAPSHOT.jar server server.yml
networks:
  opentracing:
    driver: bridge
